// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBycP6007dehA6J1zd351ikaMYLtYueTIg',
    appId: '1:1023000700204:web:2a08758bd0eb02e3783889',
    messagingSenderId: '1023000700204',
    projectId: 'solcha2024',
    authDomain: 'solcha2024.firebaseapp.com',
    storageBucket: 'solcha2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChEHzC8CQcnoZtfuHV5jBzuWfMWYTno_I',
    appId: '1:1023000700204:android:fc480b4a8486a8f7783889',
    messagingSenderId: '1023000700204',
    projectId: 'solcha2024',
    storageBucket: 'solcha2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfJlKCTItQL8rtGRLMSHsavBvBr6LUopM',
    appId: '1:1023000700204:ios:101e7535b1054cdb783889',
    messagingSenderId: '1023000700204',
    projectId: 'solcha2024',
    storageBucket: 'solcha2024.appspot.com',
    iosBundleId: 'com.example.solcha2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfJlKCTItQL8rtGRLMSHsavBvBr6LUopM',
    appId: '1:1023000700204:ios:095e8bed7695cd2e783889',
    messagingSenderId: '1023000700204',
    projectId: 'solcha2024',
    storageBucket: 'solcha2024.appspot.com',
    iosBundleId: 'com.example.solcha2024.RunnerTests',
  );
}
